name: Sync Postman Collection to GitHub

on:
  schedule:
    # Runs every hour (adjust as needed)
    - cron: '0 * * * *'
  workflow_dispatch: # Allows manual triggers

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Fetch Postman Collection
        run: |
          curl -s -H "X-API-Key: ${{ secrets.POSTMAN_API_KEY }}" \
            "https://api.getpostman.com/collections/${{ secrets.COLLECTION_ID }}" \
            -o postman-collections/your-collection.json

      - name: Commit & Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || \
            (git commit -m "Auto-update Postman Collection" && git push)